// Maps an ISO 3166-1 alpha-2 country code (as used by dxheat.com's spot "Flag"
// field) to the DXCC entity name(s) it could correspond to. Several ISO codes
// cover multiple distinct DXCC entities (e.g. "us" -> United States, Alaska,
// Hawaii each count separately for DXCC/awards purposes) — dxheat's spot feed
// doesn't carry DXCC-entity-level granularity, only the ISO flag, so this is
// inherently a many-to-one/many mapping, not a precise one. A spot is only
// ever marked "Needed" when NONE of its possible entities are in the worked
// set; if even one match is worked, or the code isn't in this table at all,
// no claim is made — biased toward silence over a wrong "needed" call.
//
// Covers the common/frequently-spotted countries. Deliberately incomplete for
// small/rare DXCC-only entities (islands, etc.) that rarely appear on a live
// spot feed anyway — those just get no badge, same as today.
export const ISO_TO_DXCC: Record<string, string[]> = {
  us: ['United States', 'Alaska', 'Hawaii'],
  ca: ['Canada'],
  mx: ['Mexico'],
  gb: ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  ie: ['Ireland'],
  fr: ['France', 'Corsica'],
  de: ['Germany'],
  it: ['Italy', 'Sardinia'],
  es: ['Spain', 'Balearic Islands', 'Canary Islands', 'Ceuta and Melilla'],
  pt: ['Portugal', 'Azores', 'Madeira Island'],
  nl: ['Netherlands'],
  be: ['Belgium'],
  lu: ['Luxembourg'],
  ch: ['Switzerland'],
  at: ['Austria'],
  li: ['Liechtenstein'],
  dk: ['Denmark'],
  se: ['Sweden'],
  no: ['Norway', 'Svalbard'],
  fi: ['Finland'],
  is: ['Iceland'],
  pl: ['Poland'],
  cz: ['Czech Republic'],
  sk: ['Slovak Republic'],
  hu: ['Hungary'],
  ro: ['Romania'],
  bg: ['Bulgaria'],
  gr: ['Greece', 'Crete', 'Dodecanese'],
  hr: ['Croatia'],
  si: ['Slovenia'],
  ba: ['Bosnia and Herzegovina'],
  rs: ['Serbia'],
  me: ['Montenegro'],
  mk: ['North Macedonia (Republic of)'],
  al: ['Albania'],
  xk: ['Kosovo'],
  ee: ['Estonia'],
  lv: ['Latvia'],
  lt: ['Lithuania'],
  by: ['Belarus'],
  ua: ['Ukraine'],
  md: ['Moldova'],
  ru: ['Russia', 'Asiatic Russia', 'Kaliningrad'],
  ge: ['Georgia'],
  am: ['Armenia'],
  az: ['Azerbaijan'],
  kz: ['Kazakhstan'],
  tr: ['Turkey'],
  cy: ['Cyprus', 'Cyprus SBA'],
  mt: ['Malta'],
  sm: ['San Marino'],
  va: ['Vatican'],
  ad: ['Andorra'],
  mc: ['Monaco'],
  gi: ['Gibraltar'],
  ax: ['Aland Islands'],
  fo: ['Faroe Islands'],
  gl: ['Greenland'],
  jp: ['Japan'],
  cn: ['China'],
  tw: ['Taiwan'],
  hk: ['Hong Kong'],
  kr: ['South Korea'],
  kp: ['North Korea'],
  mn: ['Mongolia'],
  in: ['India'],
  pk: ['Pakistan'],
  bd: ['Bangladesh'],
  lk: ['Sri Lanka'],
  np: ['Nepal'],
  mm: ['Myanmar'],
  th: ['Thailand'],
  vn: ['Vietnam'],
  kh: ['Cambodia'],
  la: ['Laos'],
  my: ['West Malaysia'],
  sg: ['Singapore'],
  id: ['Indonesia'],
  ph: ['Philippines'],
  bn: ['Brunei'],
  tl: ['Timor Leste'],
  au: ['Australia', 'Lord Howe Island', 'Norfolk Island'],
  nz: ['New Zealand', 'Chatham Islands'],
  fj: ['Fiji'],
  pg: ['Papua New Guinea'],
  nc: ['New Caledonia'],
  pf: ['French Polynesia', 'Austral Islands', 'Marquesas Islands'],
  ws: ['Samoa'],
  as: ['American Samoa', 'Swains Island'],
  to: ['Tonga'],
  vu: ['Vanuatu'],
  sb: ['Solomon Islands'],
  ki: ['Kiribati', 'Central Kiribati', 'East Kiribati'],
  tv: ['Tuvalu'],
  nr: ['Nauru'],
  pw: ['Palau'],
  fm: ['Micronesia'],
  mh: ['Marshall Islands'],
  gu: ['Guam'],
  mp: ['Mariana Islands'],
  za: ['South Africa'],
  na: ['Namibia'],
  bw: ['Botswana'],
  zw: ['Zimbabwe'],
  zm: ['Zambia'],
  mw: ['Malawi'],
  mz: ['Mozambique'],
  ls: ['Lesotho'],
  sz: ['Eswatini'],
  ao: ['Angola'],
  cd: ['Congo'],
  cg: ['Congo'],
  cm: ['Cameroon'],
  ga: ['Gabon'],
  gq: ['Equatorial Guinea'],
  ng: ['Nigeria'],
  gh: ['Ghana'],
  ci: ['Ivory Coast'],
  sn: ['Senegal'],
  ml: ['Mali'],
  bf: ['Burkina Faso'],
  ne: ['Niger'],
  td: ['Chad'],
  gm: ['The Gambia'],
  gw: ['Guinea-Bissau'],
  gn: ['Guinea'],
  sl: ['Sierra Leone'],
  lr: ['Liberia'],
  tg: ['Togo'],
  bj: ['Benin'],
  cf: ['Central African Republic'],
  cv: ['Cape Verde'],
  st: ['Sao Tome & Principe'],
  ke: ['Kenya'],
  tz: ['Tanzania'],
  ug: ['Uganda'],
  rw: ['Rwanda'],
  bi: ['Burundi'],
  et: ['Ethiopia'],
  so: ['Somalia'],
  dj: ['Djibouti'],
  er: ['Eritrea'],
  ss: ['South Sudan'],
  sd: ['Sudan'],
  eg: ['Egypt'],
  ly: ['Libya'],
  tn: ['Tunisia'],
  dz: ['Algeria'],
  ma: ['Morocco'],
  eh: ['Western Sahara'],
  mr: ['Mauritania'],
  mg: ['Madagascar'],
  mu: ['Mauritius', 'Rodriguez Island'],
  sc: ['Seychelles'],
  km: ['Comoros'],
  re: ['Reunion'],
  yt: ['Mayotte'],
  sh: ['St Helena Island'],
  il: ['Israel'],
  ps: ['Palestine'],
  jo: ['Jordan'],
  lb: ['Lebanon'],
  sy: ['Syria'],
  iq: ['Iraq'],
  ir: ['Iran'],
  sa: ['Saudi Arabia'],
  ye: ['Yemen'],
  om: ['Oman'],
  ae: ['United Arab Emirates'],
  qa: ['Qatar'],
  kw: ['Kuwait'],
  bh: ['Bahrain'],
  af: ['Afghanistan'],
  br: ['Brazil', 'Fernando de Noronha', 'Trindade and Martim Vaz Island'],
  ar: ['Argentina'],
  cl: ['Chile', 'Easter Island', 'Juan Fernandez Islands'],
  uy: ['Uruguay'],
  py: ['Paraguay'],
  bo: ['Bolivia'],
  pe: ['Peru'],
  ec: ['Ecuador', 'Galapagos Islands'],
  co: ['Colombia', 'San Andres and Providencia'],
  ve: ['Venezuela'],
  gy: ['Guyana'],
  sr: ['Suriname'],
  gf: ['French Guiana'],
  pa: ['Panama'],
  cr: ['Costa Rica'],
  ni: ['Nicaragua'],
  hn: ['Honduras'],
  sv: ['El Salvador'],
  gt: ['Guatemala'],
  bz: ['Belize'],
  cu: ['Cuba'],
  jm: ['Jamaica'],
  ht: ['Haiti'],
  do: ['Dominican Republic'],
  pr: ['Puerto Rico'],
  bs: ['Bahamas'],
  bb: ['Barbados'],
  tt: ['Trinidad and Tobago'],
  gd: ['Grenada'],
  lc: ['St Lucia'],
  vc: ['St Vincent'],
  ag: ['Antigua and Barbuda'],
  dm: ['Dominica'],
  kn: ['St Kitts and Nevis'],
  vg: ['British Virgin Islands'],
  vi: ['US Virgin Islands'],
  ai: ['Anguilla'],
  ky: ['Cayman Islands'],
  tc: ['Turks and  Caicos Islands'],
  ms: ['Montserrat'],
  bm: ['Bermuda'],
  aw: ['Bonaire', 'Curacao', 'St Martin', 'St. Maarten'],
};
